SELECT COUNT(*) AS 'Produtos Vermelhos' FROM Production.Product
WHERE COLOR = 'RED' 
AND ListPrice BETWEEN '500' AND '1000' 

SELECT COUNT(Name) FROM Production.Product
WHERE Name LIKE '%Road%'


SELECT TOP 10 * FROM Sales.SalesOrderDetail ORDER BY LineTotal ASC

SELECT SpecialOfferID, SUM(UNITPRICE) AS 'TOTAL VENDAS' FROM Sales.SalesOrderDetail
GROUP BY SpecialOfferID
ORDER BY SUM(UNITPRICE) DESC

SELECT ProductID, COUNT(ProductID) AS 'QUANTIDADE DE PRODUTOS' FROM SALES.SalesOrderDetail
GROUP BY  ProductID
ORDER BY COUNT(ProductID) DESC

SELECT AVG(LINETOTAL) AS TOTALVENDAS
FROM Sales.SalesOrderDetail

SELECT FirstName,COUNT(FIRSTNAME) AS QTDE FROM Person.Person
GROUP BY FirstName

SELECT COLOR, AVG(LISTPRICE) AS 'MEDIA DE PREÇO DE ITENS PRATA' FROM Production.Product
WHERE Color = 'SILVER'
GROUP BY Color


SELECT MiddleName, COUNT(MIDDLENAME) AS QTDE FROM Person.Person
GROUP BY MiddleName
ORDER BY MiddleName ASC

select * from Sales.SalesOrderDetail

Select ProductID, AVG (OrderQty) from Sales.SalesOrderDetail
group by ProductID 
order by ProductID DESC

SELECT TOP 10 ProductID, SUM(LineTotal) FROM Sales.SalesOrderDetail
GROUP BY ProductID
ORDER BY SUM(LINETOTAL) DESC

SELECT ProductID, COUNT(ProductID) AS QTDE, AVG(OrderQty) AS MEDIA FROM Production.WorkOrder
GROUP BY ProductID
ORDER BY COUNT(ProductID) DESC


SELECT FIRSTNAME, COUNT(FIRSTNAME) AS QTDE
FROM PERSON.PERSON 
WHERE FirstName LIKE '%A%'
GROUP BY FirstName
HAVING COUNT(FIRSTNAME) > 10
ORDER BY COUNT(FIRSTNAME) DESC



SELECT ProductID, SUM(LINETOTAL) AS 'TOTAL DE VENDAS'
FROM SALES.SalesOrderDetail
GROUP BY ProductID
HAVING SUM(LINETOTAL) BETWEEN 162000 AND 500000
ORDER BY SUM(LINETOTAL) DESC

SELECT ProductID, AVG(LineTotal) FROM Sales.SalesOrderDetail
GROUP BY ProductID
HAVING AVG(LineTotal) <= 1000


/*
SUM - SOMAR
AVG - MEDIA
MAX - VALOR MAIS ALTO
MIN - VALOR MINIMO
*/