use feminicidio_exemplo

select MUNICIPIO_CIRCUNSCRICAO from Feminicidio_exemplo
WHERE MUNICIPIO_CIRCUNSCRICAO = 'Osasco'

SELECT AVG(IDADE_PESSOA) FROM Feminicidio_exemplo

select DESC_TIPOLOCAL from Feminicidio_exemplo
WHERE DESC_TIPOLOCAL = 'Residência'

select DESC_TIPOLOCAL from Feminicidio_exemplo
WHERE DESC_TIPOLOCAL = 'Via Pública'

select DESC_TIPOLOCAL from Feminicidio_exemplo
WHERE DESC_TIPOLOCAL = 'Unidade Rural'

select DESC_TIPOLOCAL from Feminicidio_exemplo
WHERE DESC_TIPOLOCAL = 'Saúde'

SELECT MUNICIPIO_CIRCUNSCRICAO, AVG(IDADE_PESSOA) FROM Feminicidio_exemplo
WHERE MUNICIPIO_CIRCUNSCRICAO = 'CAMPINAS'
GROUP BY MUNICIPIO_CIRCUNSCRICAO

SELECT DATAHORA_REGISTRO_BO, COUNT(NUMERO_DE_VITIMAHD)  FROM Feminicidio_exemplo
WHERE DATAHORA_REGISTRO_BO BETWEEN '2022/01/01' AND '2023/01/01'
GROUP BY DATAHORA_REGISTRO_BO

SELECT * FROM Feminicidio_exemplo